### ISSUE TITLE
Inline evalated objects

### ISSUE THREAD

**Issue by alcuadrado** [paulrouget/firefox-jsterm#23]
JsTerm is looking great, but I think a killer feature of the webkit's dev tools is missing: the ability to inspect evaluated objects inline. Although it is possible with the panel, being able to do it inline is much more comfortable in my opinion (and most of my coworkers and friends agree)

**Comment by jviereck** [comment]
How about adding some commands that makes it easy to inspect an object using only a command line. Think of `$1$` etc. that is used to inspect the last queried object etc. Then one could do `$1.foo` to get all the output of `foo` on the last dumped object. With autocompletion, this might end up in a faster workflow then using the mouse and clicking on stuff.

There could also be a flag to dump a json representation of the object instead of only showing the clickable `[object ...]` thingy.

**Comment by alcuadrado** [comment]
I think the word "inspect" was miss-leading. I was talking about this: http://i.imgur.com/2rKZk.png

The object's contents can be seen inline, and not in an annoying (IMO) panel
