### ISSUE TITLE
jsterm not working in 18

### ISSUE THREAD

**Issue by aL3xa** [paulrouget/firefox-jsterm#31]
Title is pretty much self-explanatory. I installed this addon both from xpi file available on github and [addons page](https://addons.mozilla.org/en-US/firefox/addon/javascript-terminal/?src=userprofile) with no success. It works like a charm in FF 16.0.2 though, but not in my beloved early-bird aurora/nightly builds.

**Comment by blissdev** [comment]
Having the same issue on Nightly. Looks like this (http://dl.dropbox.com/u/41458/Slingshot/Pictures/Screen%20Shot%202012-11-13%20at%208.24.14%20PM.png) and is completely non-interactable.

**Comment by blissdev** [comment]
I'm going to try to set up this up locally and see if I can figure out the problem. 

@paulrouget: As someone new to firefox addon dev, any information/tips on setting this up locally?

**Comment by paulrouget** [comment]
The problem is that the internal Firefox code editor I use here has changed (the internal API). So i guess we just need to update the way we use the editor (SourceEditor object).

This addon is a restartless addon, so you only need to install this addon:
https://addons.mozilla.org/en-US/firefox/addon/autoinstaller/?src=ss
change the code, type `make`, and it should install the addon.

**Comment by blissdev** [comment]
The first error I encounter is that it can't find `WebConsoleUtils.jsm`. As I'm not too familiar with how all these things work together, I'm not sure where to look for the correct location. I will try to research more and see what I can find. Any pointers would be appreciated.

```
Timestamp: 1/1/13 9:30:06 PM
Error: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
Source File: chrome://jsterm/content/jsterm.js
Line: 4
```

**Comment by aL3xa** [comment]
Awesome, thanks!!! =)
